require "user.hot-reload"
require "user.options"
require "user.keymaps"

require "user.plugins"

-- require "user.colorscheme"
require "user.cmp"
-- require "user.lsp-inlayhints"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
-- require "user.nvim-tree"
-- require "user.bufferline"
require "user.toggleterm"
require "user.project"
require "user.impatient"
-- require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.illuminate"
-- require "user.copilot"
-- require "user.codeium"
-- require "user.tabnine"
require "user.todo-comments"
require "user.trouble"
require "user.fidget"
require "user.symbol-outline"
-- require "user.dap" -- TODO:
require "user.ts-context"
require "user.dressing" -- ui for some actions
-- require "user.cybu" -- cycle buffers with ui
require "user.notify"
require "user.nvim-webdev-icons"
require "user.hop"
require "user.bookmark"
require "user.harpoon"
require "user.noice"
require "user.navic"
reload "user.lualine"
