return {}
  -- 'kyazdani42/nvim-tree.lua',
  -- config = function()
  --
  --   local status_ok, nvim_tree = pcall(require, "nvim-tree")
  --   local config_status_ok, nvim_tree_config = pcall(require, "nvim-tree.config")
  --   local icons = require "user.icons"
  --   local tree_cb = nvim_tree_config.nvim_tree_callback
  --   local utils = require "nvim-tree.utils"
  --
  --   ---@diagnostic disable-next-line: unused-local
  --   local function notify_level(level)
  --     return function(msg)
  --       vim.schedule(function()
  --         vim.api.nvim_echo({ { msg, "WarningMsg" } }, false, {})
  --       end)
  --     end
  --   end
  --   local function open_nvim_tree(data)
  --     -- buffer is a [No Name]
  --     local no_name = data.file == "" and vim.bo[data.buf].buftype == ""
  --     -- buffer is a directory
  --     local directory = vim.fn.isdirectory(data.file) == 1
  --     if not no_name and not directory then
  --       return
  --     end
  --     -- change to the directory
  --     if directory then
  --       vim.cmd.cd(data.file)
  --     end
  --     -- open the tree
  --     -- require("nvim-tree.api").tree.open()
  --   end
  --   vim.api.nvim_create_autocmd({ "VimEnter" }, { callback = open_nvim_tree })
  --   -- utils.notify.warn = notify_level(vim.log.levels.WARN)
  --   -- utils.notify.error = notify_level(vim.log.levels.ERROR)
  --   -- utils.notify.info = notify_level(vim.log.levels.INFO)
  --   -- utils.notify.debug = notify_level(vim.log.levels.DEBUG)
  --
  --   nvim_tree.setup {
  --     -- actions = {
  --     --   change_dir = {
  --     --     enable = true,
  --     --     global = true,
  --     --     restrict_above_cws = false,
  --     --   },
  --     -- },
  --     hijack_directories = {
  --       enable = false,
  --     },
  --     -- update_to_buf_dir = {
  --       --   enable = false,
  --       -- },
  --       -- disable_netrw = true,
  --       -- hijack_netrw = true,
  --       -- open_on_setup = true,
  --       -- ignore_ft_on_setup = {
  --       --   "startify",
  --       --   "dashboard",
  --       --   "alpha",
  --       -- },
  --       filters = {
  --         custom = { ".git" },
  --         exclude = { ".gitignore" },
  --       },
  --       -- auto_close = true,
  --       -- open_on_tab = false,
  --       -- hijack_cursor = false,
  --       update_cwd = true,
  --       -- update_to_buf_dir = {
  --       --   enable = true,
  --       --   auto_open = true,
  --       -- },
  --       -- --   error
  --       -- --   info
  --       -- --   question
  --       -- --   warning
  --       -- --   lightbulb
  --       renderer = {
  --         add_trailing = false,
  --         group_empty = false,
  --         highlight_git = false,
  --         highlight_opened_files = "none",
  --         root_folder_modifier = ":t",
  --         indent_markers = {
  --           enable = false,
  --           icons = {
  --             corner = "└ ",
  --             edge = "│ ",
  --             none = "  ",
  --           },
  --         },
  --         icons = {
  --           webdev_colors = true,
  --           git_placement = "before",
  --           padding = " ",
  --           symlink_arrow = " ➛ ",
  --           show = {
  --             file = true,
  --             folder = true,
  --             folder_arrow = true,
  --             git = true,
  --           },
  --           glyphs = {
  --             default = "",
  --             symlink = "",
  --             folder = {
  --               arrow_open = icons.ui.ArrowOpen,
  --               arrow_closed = icons.ui.ArrowClosed,
  --               default = "",
  --               open = "",
  --               empty = "",
  --               empty_open = "",
  --               symlink = "",
  --               symlink_open = "",
  --             },
  --             git = {
  --               unstaged = "",
  --               staged = "S",
  --               unmerged = "",
  --               renamed = "➜",
  --               untracked = "U",
  --               deleted = "",
  --               ignored = "◌",
  --             },
  --           },
  --         },
  --       },
  --       diagnostics = {
  --         enable = true,
  --         icons = {
  --           hint = icons.diagnostics.Hint,
  --           info = icons.diagnostics.Information,
  --           warning = icons.diagnostics.Warning,
  --           error = icons.diagnostics.Error,
  --         },
  --       },
  --       update_focused_file = {
  --         enable = true,
  --         update_cwd = true,
  --         ignore_list = {},
  --       },
  --       -- system_open = {
  --       --   cmd = nil,
  --       --   args = {},
  --       -- },
  --       -- filters = {
  --       --   dotfiles = false,
  --       --   custom = {},
  --       -- },
  --       git = {
  --         enable = true,
  --         ignore = true,
  --         timeout = 500,
  --       },
  --       view = {
  --         width = 30,
  --         -- height = 30,
  --         hide_root_folder = false,
  --         side = "left",
  --         -- auto_resize = true,
  --         mappings = {
  --           custom_only = false,
  --           list = {
  --             { key = { "l", "<CR>", "o" }, cb = tree_cb "edit" },
  --             { key = "h", cb = tree_cb "close_node" },
  --             { key = "v", cb = tree_cb "vsplit" },
  --           },
  --         },
  --         number = true,
  --         relativenumber = true,
  --       },
  --     }
  --
  --   end
  -- }
